Add Host.pm to ignore list and fix date error.
Currently permabit-Core is not able to build due to the
following error:

error: Installed (but unpackaged) file(s) found:
/usr/share/perl5/vendor_perl/Permabit/Internals/CheckServer/Host.pm
bogus date in %changelog: Wed Jun 06 2023 Susan LeGendre-McGhee 
  <slegendr@redhat.com> - 1.03-35
bogus date in %changelog: Tue Jun 05 2023 Susan LeGendre-McGhee 
  <slegendr@redhat.com> - 1.03-34
Installed (but unpackaged) file(s) found:
/usr/share/perl5/vendor_perl/Permabit/Internals/CheckServer/Host.pm

We need this package because platformUtil.pm is installed from 
  this package, and it contains the F39 changes.

Pair: awalsh

.../perl-Permabit-Core.spec
Fix the above error:
Add Host.pm to the perl-Permabit-NotUsed list. The host.pm is being
  handled in checkServer package.
Fix date error, weekday is off by one day.

[git-p4: depot-paths = "//eng/common/": change = 159122]